#!/bin/bash
#SBATCH --job-name=cobert_race_imp_test1
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 0-12:00:00
#SBATCH --cpus-per-task=18
#SBATCH -o cobert_winoGrande_random_test.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate slak


python examples/roberta/wsc/evaluate.py