#!/bin/bash
#SBATCH --job-name=reberta_LTH_noemb_nocla_noLRR
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 0-2:00:00
#SBATCH --cpus-per-task=18
#SBATCH -o reberta_LTH_noemb_nocla_noLRR.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate prune_cry


python examples/roberta/commonsense_qa/evaluate_lth.py