#!/bin/bash
#SBATCH --job-name=roberta_gmp_no_embedding_no_classifier_LRR_5epoch_perpruning_lr5e05_test
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 0-10:00:00
#SBATCH --cpus-per-task=18
#SBATCH -o roberta_gmp_no_embedding_no_classifier_LRR_5epoch_perpruning_lr5e05_test.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate slak


python examples/roberta/commonsense_qa/evaluate_lth.py